extend = "../Makefile.toml"

[tasks.uf2]
command = "elf2uf2-rs"
args = ["../target/thumbv6m-none-eabi/release/ledmatrix", "../target/thumbv6m-none-eabi/release/ledmatrix.uf2"]
dependencies = ["build-release"]
install_crate = "elf2uf2-rs"
