[package]
edition = "2021"
name = "lotus_inputmodules"
version = "0.1.2-pre"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7.3"
embedded-hal = { version = "0.2.7", features = ["unproven"] }

defmt = "0.3"
defmt-rtt = "0.4"

#panic-probe = { version = "0.3", features = ["print-defmt"] }
rp2040-panic-usb-boot = { git = "https://github.com/rwalkr/rp2040-panic-usb-boot" }

# Not using a BSP, we've got a Lotus BSP's locally in this crate
rp2040-hal = { version="0.7", features=["rt", "critical-section-impl"] }
rp2040-boot2 = "0.2"

# USB Serial
usb-device= "0.2.9"

heapless = "0.7.9"
usbd-serial = "0.1.1"
usbd-hid = "0.5.1"
fugit = "0.3.6"

# LED Matrix
is31fl3741 = { git = "https://github.com/JohnAZoidberg/is31fl3741", branch = "all-at-once", optional = true }


# B1 Display
display-interface-spi = { version = "0.4.1", optional = true }
mipidsi = { version = "0.6.0", optional = true }
embedded-graphics = { version = "0.7", optional = true }
tinybmp = { version = "0.4.0", optional = true }

# C1 Minimal
smart-leds = { version = "0.3.0", optional = true }
ws2812-pio = { version = "0.5.0", optional = true }

[lib]
name = "lotus_input"
path = "src/lib.rs"

[[bin]]
name = "ledmatrix"
required-features = ["ledmatrix"]

[[bin]]
name = "b1display"
required-features = ["b1display"]

[[bin]]
name = "c1minimal"
required-features = ["c1minimal"]

[features]
ledmatrix = [ "is31fl3741" ]
b1display = [ "display-interface-spi", "mipidsi", "embedded-graphics", "tinybmp" ]
c1minimal = [ "smart-leds", "ws2812-pio" ]

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
# To allow single-stepping through code use 0. Will cause timing issues, though
opt-level = 3
overflow-checks = true

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
