name: Firmware CI Checks

on:
  push

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  building:
    name: Building
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        run: rustup show

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - run: cargo install flip-link
      - run: cargo make --cwd b1display
      - run: cargo make --cwd c1minimal
      - run: cargo make --cwd ledmatrix build-release
      - run: cargo make --cwd b1display build-release
      - run: cargo make --cwd c1minimal build-release

      - name: Convert to UF2 format
        run: |
            sudo apt-get update
            sudo apt-get install -y libudev-dev
            cargo install elf2uf2-rs
            elf2uf2-rs target/thumbv6m-none-eabi/release/b1display b1display.uf2
            elf2uf2-rs target/thumbv6m-none-eabi/release/c1minimal c1minimal.uf2
            elf2uf2-rs target/thumbv6m-none-eabi/release/ledmatrix ledmatrix.uf2

      - name: Upload UF2 files
        uses: actions/upload-artifact@v3
        with:
          name: inputmodule_fw_uf2
          path: |
            b1display.uf2
            c1minimal.uf2
            ledmatrix.uf2

      - name: Convert to bin format
        run: |
            sudo apt-get update
            sudo apt-get install -y llvm
            llvm-objcopy -O binary target/thumbv6m-none-eabi/release/b1display b1display.bin
            llvm-objcopy -O binary target/thumbv6m-none-eabi/release/c1minimal c1minimal.bin
            llvm-objcopy -O binary target/thumbv6m-none-eabi/release/ledmatrix ledmatrix.bin

      - name: Upload bin files
        uses: actions/upload-artifact@v3
        with:
          name: inputmodule_fw_bin
          path: |
            b1display.bin
            c1minimal.bin
            ledmatrix.bin

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Rust toolchain
        run: rustup show

      - run: |
          cargo clippy -p b1display -- --deny=warnings
          cargo clippy -p c1minimal -- --deny=warnings
          cargo clippy -p ledmatrix -- --deny=warnings

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Rust toolchain
        run: rustup show

      - run: cargo fmt --all -- --check
